import { useState } from "react";
import API from "../services/api";
import jsPDF from "jspdf";

function UploadMRI() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);

  const [prediction, setPrediction] = useState("");
  const [confidence, setConfidence] = useState("");
  const [patientName, setPatientName] = useState("");

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];

    setFile(selectedFile);

    if (selectedFile) {
      setPreview(URL.createObjectURL(selectedFile));
    }
  };

  const handleUpload = async () => {
    if (!file) {
      alert("Please select MRI image");
      return;
    }

    const formData = new FormData();

    formData.append(
      "patient_name",
      patientName
    );

    formData.append(
      "file",
      file
    );

    try {
      setLoading(true);

      const response = await API.post(
        "/upload",
        formData
      );

      setPrediction(
        response.data.prediction
      );

      setConfidence(
        response.data.confidence
      );

      setLoading(false);
    } catch (error) {
      setLoading(false);

      console.log(error);

      if (error.response) {
        alert(
          error.response.data.error ||
          JSON.stringify(
            error.response.data
          )
        );
      } else {
        alert(error.message);
      }
    }
  };

  const getColor = () => {
    if (prediction === "notumor")
      return "green";

    if (prediction === "glioma")
      return "red";

    if (prediction === "meningioma")
      return "orange";

    if (prediction === "pituitary")
      return "purple";

    return "gray";
  };

  const downloadReport = () => {
    const doc = new jsPDF();

    const currentDate =
      new Date().toLocaleDateString();

    doc.setFillColor(
      15,
      23,
      42
    );

    doc.rect(
      0,
      0,
      210,
      30,
      "F"
    );

    doc.setTextColor(
      255,
      255,
      255
    );

    doc.setFontSize(22);

    doc.text(
      "SND NeuroVision AI",
      20,
      18
    );

    doc.setFontSize(10);

    doc.text(
      "AI Powered Brain Tumor Detection Platform",
      20,
      25
    );

    doc.setTextColor(
      0,
      0,
      0
    );

    doc.setFontSize(18);

    doc.text(
      "MRI Analysis Report",
      65,
      45
    );

    doc.setFontSize(12);

    doc.text(
      `Patient Name: ${patientName}`,
      20,
      65
    );


    doc.text(
      `Date: ${currentDate}`,
      20,
      75
    );

    doc.line(
      20,
      95,
      190,
      95
    );

    doc.setFillColor(
      240,
      240,
      240
    );

    doc.roundedRect(
      20,
      105,
      170,
      55,
      3,
      3,
      "F"
    );

    doc.setFontSize(16);

    doc.text(
      "AI Diagnosis Result",
      30,
      120
    );

    doc.setFontSize(14);

    doc.text(
      `Tumor Type: ${prediction.toUpperCase()}`,
      30,
      138
    );

    doc.text(
      `Confidence Score: ${confidence}%`,
      30,
      150
    );

    doc.setFontSize(14);

    doc.text(
      "AI Remarks",
      20,
      180
    );

    let remarks =
      prediction === "notumor"
        ? "No tumor detected. MRI scan appears normal."
        : `Possible ${prediction} tumor detected. Further medical evaluation is recommended.`;

    doc.setFontSize(11);

    doc.text(
      remarks,
      20,
      192,
      {
        maxWidth: 160,
      }
    );

    doc.line(
      20,
      250,
      190,
      250
    );

    doc.setFontSize(10);

    doc.text(
      "Generated by SND NeuroVision AI",
      20,
      260
    );

    doc.text(
      "This report is AI-assisted and should not replace professional medical diagnosis.",
      20,
      268
    );

    doc.text(
      "Authorized Digital Signature",
      130,
      260
    );

    doc.save(
      `${patientName}_MRI_Report.pdf`
    );
  };

  return (
    <div
      style={{
        maxWidth: "1100px",
        margin: "40px auto",
        padding: "20px",
      }}
    >
      {/* Header */}
      <div
        style={{
          background:
            "linear-gradient(135deg,#2563eb,#7c3aed)",
          color: "white",
          padding: "40px",
          borderRadius: "20px",
          textAlign: "center",
          marginBottom: "30px",
        }}
      >
        <h1>🧠 MRI Analysis Dashboard</h1>

        <p
          style={{
            marginTop: "10px",
            fontSize: "18px",
          }}
        >
          Upload MRI scans and receive instant
          AI-powered brain tumor diagnosis.
        </p>
      </div>

      {/* Stats Cards */}
      <div
        style={{
          display: "flex",
          gap: "20px",
          flexWrap: "wrap",
          marginBottom: "30px",
          justifyContent: "center",
        }}
      >
        <div className="card">
          🧠 AI Powered
        </div>

        <div className="card">
          📊 98% Accuracy
        </div>

        <div className="card">
          ⚡ Fast Detection
        </div>
      </div>

      {/* Upload Section */}
      <div
        style={{
          background: "white",
          padding: "30px",
          borderRadius: "20px",
          boxShadow:
            "0 10px 30px rgba(0,0,0,0.1)",
        }}
      >
        <h2
          style={{
            marginBottom: "20px",
          }}
        >
          Patient Information
        </h2>

        <input
          type="text"
          placeholder="Enter Patient Name"
          value={patientName}
          onChange={(e) =>
            setPatientName(e.target.value)
          }
          style={{
            width: "100%",
            padding: "15px",
            borderRadius: "10px",
            border: "1px solid #ddd",
            marginBottom: "20px",
            fontSize: "16px",
          }}
        />

        <input
          type="file"
          onChange={handleFileChange}
        />

        <br />
        <br />

        <button
          onClick={handleUpload}
          style={{
            padding: "15px 35px",
            background:
              "linear-gradient(135deg,#2563eb,#7c3aed)",
            color: "white",
            border: "none",
            borderRadius: "10px",
            fontWeight: "bold",
            fontSize: "16px",
            cursor: "pointer",
          }}
        >
          🚀 Analyze MRI
        </button>
      </div>

      {/* MRI Preview */}
      {preview && (
        <div
          style={{
            marginTop: "40px",
            background: "white",
            padding: "25px",
            borderRadius: "20px",
            boxShadow:
              "0 10px 25px rgba(0,0,0,0.1)",
            textAlign: "center",
          }}
        >
          <h2>🖼 MRI Preview</h2>

          <img
            src={preview}
            alt="MRI"
            width="400"
            style={{
              marginTop: "20px",
              borderRadius: "15px",
              boxShadow:
                "0 10px 25px rgba(0,0,0,0.2)",
            }}
          />
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div
          style={{
            marginTop: "40px",
            background: "white",
            padding: "30px",
            borderRadius: "20px",
            textAlign: "center",
            boxShadow:
              "0 10px 25px rgba(0,0,0,0.1)",
          }}
        >
          <h2>🔄 Analyzing MRI...</h2>

          <p>
            AI is processing the MRI scan.
            Please wait...
          </p>
        </div>
      )}

      {/* Result */}
      {prediction && (
        <div
          style={{
            marginTop: "40px",
            background: "white",
            padding: "30px",
            borderRadius: "20px",
            boxShadow:
              "0 10px 25px rgba(0,0,0,0.1)",
          }}
        >
          <h2>📄 AI Analysis Report</h2>

          <p>
            <strong>Patient:</strong>{" "}
            {patientName ||
              "Not Provided"}
          </p>

          <h3
            style={{
              marginTop: "20px",
            }}
          >
            Tumor Type
          </h3>

          <div
            style={{
              background: getColor(),
              color: "white",
              display: "inline-block",
              padding: "12px 25px",
              borderRadius: "25px",
              fontWeight: "bold",
              marginTop: "10px",
            }}
          >
            {prediction.toUpperCase()}
          </div>

          <h3
            style={{
              marginTop: "25px",
            }}
          >
            Confidence Score
          </h3>

          <div
            style={{
              width: "100%",
              background: "#ddd",
              borderRadius: "15px",
            }}
          >
            <div
              style={{
                width: `${confidence}%`,
                background:
                  "linear-gradient(135deg,#2563eb,#7c3aed)",
                color: "white",
                padding: "12px",
                borderRadius: "15px",
                textAlign: "center",
                fontWeight: "bold",
              }}
            >
              {Number(confidence).toFixed(2)}%
            </div>
          </div>

          <button
            onClick={downloadReport}
            style={{
              marginTop: "25px",
              padding: "15px 30px",
              background: "#16a34a",
              color: "white",
              border: "none",
              borderRadius: "10px",
              fontWeight: "bold",
              cursor: "pointer",
            }}
          >
            📥 Download PDF Report
          </button>
        </div>
      )}
    </div>
  );
}

export default UploadMRI;